### ISSUE TITLE
mb_strlen(): Unknown encoding "8BIT" error

### ISSUE THREAD

**Issue by murat-aksoy** [pheanstalk/pheanstalk#200]
https://github.com/pheanstalk/pheanstalk/blob/c25e4b463758ea8dc2eef0560d29dbc7c4200d94/src/Socket/SocketSocket.php#L99

Hi guys,
Yesterday, I installed this package on a system which has these :
Ubuntu 16.04
Apache 2 
php 7.2.19

While reading the payload from queue PHP throws this fatal error :
mb_strlen(): Unknown encoding "8BIT"

then I replaced the 8BIT text to 8bit and it worked. As I remember ubuntu server's local language is Turkish. Do you think this may be the reason? Server is at another location so I can not test it now.

**Comment by SamMousa** [comment]
This error is not related to this library.

**Comment by Grisgruis** [comment]
Haha thanks for this issue! I just found a really weird bug in our system where jobs were being kept in status reserved, Ended up due to enabling placing orders in turkish with a tr_TR locale, throwing an `Unknown encoding "8BIT"` and breaking my job handlers. 

Massive thanks for the hint above :+1:
