### ISSUE TITLE
Deleting Job based on Displayname doesn't work

### ISSUE THREAD

**Issue by aconital** [pheanstalk/pheanstalk#212]
I'm trying to delete some jobs based on their DisplayName attribute that I get via getData(). My script removes it from the ready pile and puts it in reserved but the job doesn't get deleted and as soon as I terminate my script the jobs go back to ready pile again. If I don't provide the $jobName 
 which makes my code go to the else condtion then the job gets removed properly. Is there something happening in getData() that prevents the job from being deleted? Here is my script:

        
        
         
 
        $queue = $this->queue;
        $jobName = $this->job;
        $pheanstalk = \Illuminate\Support\Facades\Queue::getPheanstalk();
        $pheanstalk->useTube($queue);
        $pheanstalk->watch($queue);
        while ($job = $pheanstalk->reserve(0)) {
            if($jobName) {
                $jobData = json_decode($job->getData(),true);
                $displayNameChunks = explode('\\',$jobData['displayName']);
                $jobClassName = $displayNameChunks[count($displayNameChunks)-1];
                if($jobName === $jobClassName) {
                    $pheanstalk->delete($job);
                }
            }
            else {
                $pheanstalk->delete($job);
            }

        }

**Comment by SamMousa** [comment]
This doesn't feel like a library issue to me. Is delete actually being called?

Also it seems you're using an older version of the library.

**Comment by aconital** [comment]
@SamMousa I'm using this version "pda/pheanstalk": "^4.0"

**Comment by SamMousa** [comment]
Ah; I was wondering about your version since you use `reserve()` but the current version doesn't take an argument for `reserve()`.

The beanstalkd protocol here (https://github.com/beanstalkd/beanstalkd/blob/master/doc/protocol.txt#L82) shows that after deleting it should go poof.

> Is there something happening in getData() that prevents the job from being deleted? 

Definitely not, the job is an immutable value object.  (https://github.com/pheanstalk/pheanstalk/blob/master/src/Job.php)

Could be that strange stuff is happening because you're not releasing the jobs that you do not want to delete. At some point you will have a lot of jobs reserved, when the first one of those reaches its TTR you could be getting exceptions. (But that's not what you're getting).

Let me know if you find what's the causing the behavior; I expect the job matching is faulty not beanstalk or Pheanstalk.

**Comment by aconital** [comment]
@SamMousa You are right. It's going back to ready because I was not releasing them. But the problem with releasing when they don't match is that it falls into an infinite loop as it's always checking the top of the queue so it keeps checking the same job over and over. Is there a way to scan all the job?

**Comment by SamMousa** [comment]
You could bury all of them and after you're done kick them. Honestly I think iterating over the queue is not something you should do if it can be avoided at all.
