### ISSUE TITLE
Socker error 115

### ISSUE THREAD

**Issue by juriem-paxful** [pheanstalk/pheanstalk#224]
Some times got an error Socket error 115
```php
vendor/pda/pheanstalk/src/SocketFactory.php(69): Pheanstalk\Socket\SocketSocket->__construct('x.x.x.x', xxxxx, 2)
vendor/pda/pheanstalk/src/SocketFactory.php(85): Pheanstalk\SocketFactory->createSocketSocket()
vendor/pda/pheanstalk/src/Connection.php(129): Pheanstalk\SocketFactory->create()
vendor/pda/pheanstalk/src/Connection.php(74): Pheanstalk\Connection->getSocket()
vendor/pda/pheanstalk/src/Pheanstalk.php(369): Pheanstalk\Connection->dispatchCommand(Object(Pheanstalk\Command\UseCommand))
vendor/pda/pheanstalk/src/Pheanstalk.php(319): Pheanstalk\Pheanstalk->dispatch(Object(Pheanstalk\Command\UseCommand))
vendor/laravel/framework/src/Illuminate/Queue/BeanstalkdQueue.php(93): Pheanstalk\Pheanstalk->useTube('my_tube')
```
Can not reproduce this at localhost. Appears only in production.

**Comment by SamMousa** [comment]
This could be caused by the call to `socket_set_block()` failing.
In that case the socket would be non-blocking meaning connect would return immediately before completing the connection.

I could add some code to check the return value, but that will not resolve the issue you're seeing. All it would do is provide a better message for future research.

You can try this yourself by changing `SocketSocket` line 42.
Currently: `socket_set_block($this->socket);`

Change to: `if (socket_set_block($this->socket) === false) { throw new \Exception('Failed to set socket to blocking'); }` 

This should give you a new exception, confirming that the socket is nonblocking which could cause the error you mentioned.

**Comment by juriem-paxful** [comment]
Thanks. 

Is it possible to reproduce such situation at local machine?

**Comment by SamMousa** [comment]
I wouldn't know how. It could be an OS thing but could also have to do with specific things like network latency

**Comment by SamMousa** [comment]
From v4.03 an exception will be thrown if we fail to set the socket to blocking mode. That should mitigate the issue you are getting and would instead result in a hard-fail earlier.

**Comment by HelloZouYou** [comment]
hello, in version 4.0.3, i also got the error "Pheanstalk\Exception\ConnectionException: Socket error 115: Operation now in progress"
cloud i get any help

**Comment by SamMousa** [comment]
This is an error from the network stack, it is not related to this library.
