### ISSUE TITLE
Fix overflowing integer job IDs on 32-bit systems

### ISSUE THREAD

**Issue by fanis** [pheanstalk/pheanstalk#228]
On 32-bit systems, integer max size is 2147483647 which increases the odds of a long-running Beanstalkd server having job IDs that go over that limit.

When that happens Pheanstalk is unable to process jobs or perform actions on them because it casts the job ID to an integer ([see example in RESERVE response](https://github.com/pheanstalk/pheanstalk/blob/6165573aad525d39b3ac8ae916214cb483a61263/src/Command/ReserveCommand.php#L30) and in [STATS job-id](https://github.com/pheanstalk/pheanstalk/blob/6165573aad525d39b3ac8ae916214cb483a61263/src/Command/StatsJobCommand.php#L17)). In these cases it will RESERVE a job but then any other command on it will be on job ID 2147483647, which either be the wrong one or won't exist.

I propose allowing job IDs to be strings so that they are not bound by such max sizes, though this might break client code that expects it to be an integer. Thoughts?

**Comment by SamMousa** [comment]
Hmm, I think this is a very unlikely scenario. It amounts to ~68 jobs per second for a full year... 
Combined with the fact that there is not much reason to run on 32 bit I don't think we'll support this use case for now.

Of course, in theory, since we have the abstraction in the form of a `JobId`, we could / should change our internal code to be less dependent on using ints, but instead have dependencies on `JobId`, which then will have the dependency on ints or strings or floats.

**Comment by fanis** [comment]
You'd be surprised how quickly you can reach 2147483647 jobs :) Restarting beanstalk has not been necessary, a testament to its stability.

**Comment by SamMousa** [comment]
You can, but it's not a very common scenario.. Combine that with the fact that 32bit environments are also not very common...

On the other hand, if we were to change the the type of a job ID from int to string now would be the time (since i'm working on major version 5, where we have some freedom to break BC)..

The biggest issue will be people storing job ids in the database as integers, they would have to adapt their code. Also, if we specify `string` as the type it then becomes harder to enforce the fact that is actually a numeric string..

One way to solve it mostly internally is to keep the public `getId()` as returning an int, but add another `getIdAsString(): string`.
That way on 64bit nothing changes. Any `Job` or `JobId` object created by the library will be able to work on 32bit as well.

People storing IDs in databases will get the same that they get now, people on 32 bit systems should then change their code to store it as a string instead....

**Comment by fanis** [comment]
I understand. A new `getIdAsString()` should be fine for using the ID externally, however the way I am reading the code a few `sprintf` calls applied to `$this->jobId` when writing out Beanstalk protocol commands must also change to consider it a string instead of an int with `%s` instead of `%u`.

**Comment by SamMousa** [comment]
Yeah, but those should be phased out anyway, they are inconsistent and make for error messages in weird places.
I'd prefer code like `throw SomeCaseException::forJob($job)` which can then use the new method to set its message, if it even cares about including it...

**Comment by SamMousa** [comment]
In v5 I've changed everything to use a string (wrapped in a `JobIdInterface`).
Please review the implementation and provide any feedback on the implementation in new issues or on the PR.
