### ISSUE TITLE
Should not suppress error with @

### ISSUE THREAD

**Issue by yellow1912** [pheanstalk/pheanstalk#231]
This is a very edge-case error, but I was trying to use pheanstalkd with swoole, and I got a silent error (script just quits without saying anything). After much debugging I found this line

`if (@socket_connect($this->socket, $addresses[0], $port) === false) `

This one is inside Socket/SocketSocket.php and the @ symbol suppresses possible error reporting. I think it's better to just let the error shows because if socket cannot connect it is a fatal error anyhow. This one is removed in php8 anyway: https://www.php.net/manual/en/language.operators.errorcontrol.php

**Comment by SamMousa** [comment]
If you look at the code it just catches  the warning and throws and an exception. That's perfectly fine, since your code will be better equipped to deal with exceptions than warnings.

This won't be changed in a minor release since it is a BC break. For php 8 it is removed, but there the core libraries themselves will throw exceptions.

**Comment by yellow1912** [comment]
I see, I think perhaps it's the weird combination of swoole and and its socket handling that causes a silent exception (no error thrown at all).
