### ISSUE TITLE
Request, make default TTR settable.

### ISSUE THREAD

**Issue by hayden-t** [pheanstalk/pheanstalk#243]
Would be nice to have it accessible, maybe even other default params too. thanks.

**Comment by SamMousa** [comment]
I think this can be easily implemented in user code.

Instead of injecting the `Pheanstalk` class as a direct dependency just create your own adapter / wrapper that behaves the way you like it.
This is cleaner anyway because it separates your code from this library, if you ever switch than all you have to do is change your adapter.
