### ISSUE TITLE
Job TTR and DEADLINE_SOON notification

### ISSUE THREAD

**Issue by Boengar** [pheanstalk/pheanstalk#268]
Hi! 

Normally beanstalkd replies with DEADLINE_SOON once the TTR of a Job is near it's end. In that time you would have either time to touch it to prolong the TTR or stop the execution, because the Job will be released.

However with Pheanstalk I don't receive this kind of message. 
In long running operations the job silently get's freed and can be processed by another worker. Meaning the same Job can processed multiple times concurrently.
Now I could just touch the Job preemptively or increase the TTR of all producers, but that would be just a workaround.

Am I missing something? I would expect some kind of event/callback on the Job that I can get that DEADLINE_SOON notification.
Here is some sample code I tried to reproduce that:
```php    
public function reserve()
    {
        $pheanstalk = Pheanstalk::create('beanstalkd');

        // Queue a Job
        try {
            while (true) {
                print_r('Getting Job' . PHP_EOL);
                $job = $pheanstalk
                    ->watch('test')
                    ->ignore('default')
                    ->reserve();
                    // ->reserveWithTimeout(0);
                print_r($job);

                print_r('##############!');
                if ($job) {
                    $payload = $job->getData();
                    print_r($payload . PHP_EOL);
                    //processing the job long running
                    sleep(70);
                    // $pheanstalk->delete($job);
                    print_r('Job done' . PHP_EOL);
                }
                sleep(1);
            }
        } catch (\Exception $e) {
            print_r($e);
        }
    }
```

**Comment by SamMousa** [comment]
Beanstalk only emits that when you send a (new) reserve command. The protocol does not allow for server based initiation.
If possible you should run `->touch($job)` during your long running job so that beanstalk refreshes the TTR.

From https://github.com/beanstalkd/beanstalkd/blob/master/doc/protocol.txt
> During the TTR of a reserved job, the last second is kept by the server as a
safety margin, during which the client will not be made to wait for another
job. If the client issues a reserve command during the safety margin, or if
the safety margin arrives while the client is waiting on a reserve command,
the server will respond with:
```
DEADLINE_SOON\r\n
```

In PHP (at least with the Pheanstalk client) you're never doing the job while waiting on a reservation for another.

Hope this clarifies things.
