### ISSUE TITLE
v5 release notes / migration guide

### ISSUE THREAD

**Issue by kudlav** [pheanstalk/pheanstalk#269]
Hi,
I'd like to upgrade the package from v4 to v5, but I couldn't find migration guide or changelog for v5. This major version has breaking changes that should be documented.

https://github.com/pheanstalk/pheanstalk/releases/tag/v5.0.0

https://github.com/pheanstalk/pheanstalk/tree/v5.0.0?tab=readme-ov-file#history

**Comment by SamMousa** [comment]
Hi kudlav, i fully agree!

Note that no one will be taken by surprise that a major version has breaking changes since that is the point of tagging a major version change. That said id love to see a guide and some better docs! Are you up for creating some material?

**Comment by kudlav** [comment]
Sorry, I'm not going to do reverse engineering of your commits.😕
Methods changed in an undocumented way and I'm a little scared of that and by your approach.

**Comment by SamMousa** [comment]
> Sorry, I'm not going to do reverse engineering of your commits.

I think that's a bit of an exaggeration.

> Methods changed in an undocumented way 

Did they? All interface methods are documented. The types changed, they became more strict. But since this is a new major version it is expected to break. Furthermore this kind of breakage is fully automatically detectable by proper tooling. 

> and I'm a little scared of that and by your approach.

I can't tell you how to feel... but I'm unclear on what specifically scares you? Using static analysis & automated tests?
I'll tell you how I feel when getting reactions like yours: I feel irritated when developers who get to use code that I wrote for free feel entitled and start making demands without offering anything in return..

If you want to make specific recommendations or suggestestions feel free to go ahead; I get especially excited about PRs that I can just add without requiring me to do all of the work!

**Comment by SamMousa** [comment]
But can you tell us here, in this ticket, what specifically you ran into and what caught you by surprise?

For me it went like this:

1. You update from v4 to v5.
2. You ran PHPStan and it gave you a lot of errors due to changed signatures. You fixed them.
3. It works

**Comment by kudlav** [comment]
Hi, how was it resolved?

**Comment by SamMousa** [comment]
Ah apologies, my bad.

**Comment by kudlav** [comment]
Hi, it's a shame you don't plan to add release notes to v5. 
But why don't keep it open so anyone can try to do so or find this issue when migrating their apps.
